import type { SegmentDef, SegmentKey } from "../types";

/**
 * Zentrale Definition aller Segmente.
 *
 * Spielregeln (auch in README):
 *  - Bissen (Kopf-Standardwaffe)   = 1 Segment Reichweite
 *  - Schall                         = 3 Segmente
 *  - Laser                          = 6 Segmente
 *  - Kastanie                       = 0 Segmente (fällt direkt am Segment)
 *  - Raketenwerfer                  = 10 Segmente
 *  - Granatwerfer                   = 4 Segmente (Flächen-/Feuerschaden über Zeit)
 *  - Stachelwerfer                  = 3 Segmente (Gift DoT)
 *  - Honigpumpe                     = 4 Segmente (Slow 6s, 60%)
 *  - Blasebalg                      = 3 Segmente (Push 3 Segmente)
 *  - Flammenwerfer                  = 2 Segmente (Feuer)
 *  - Spinnenest                     = spawnt alle 8s eine Spinne
 *  - Larven                         = spawnt 3 Maden beim Tod des Wurms
 *
 * speedFaktor < 1 bremst, > 1 beschleunigt. Beine sind das einzige Segment > 1.
 */
export const SEGMENTE: Record<SegmentKey, SegmentDef> = {
  beine: {
    key: "beine",
    name: "Beine",
    beschreibung: "Macht den Wurm schneller. Standardmäßig freigeschaltet.",
    farbe: "bg-amber-600",
    freischaltApfel: 0,
    freischaltSternanis: 0,
    forschungSteigerung: 1.8,
    blattKosten: 3,
    sternanisBauAb4: 0,
    hp: [10, 14, 19, 25, 32],
    schaden: [0, 0, 0, 0, 0],
    speedFaktor: 1.25,
    waffe: "keine",
    reichweite: 0,
    feuerCooldown: 0,
    basis: true,
  },
  mg: {
    key: "mg",
    name: "MG",
    beschreibung: "Standard-Maschinengewehr. Standardmäßig freigeschaltet.",
    farbe: "bg-slate-500",
    freischaltApfel: 0,
    freischaltSternanis: 0,
    forschungSteigerung: 1.9,
    blattKosten: 4,
    sternanisBauAb4: 5,
    hp: [12, 16, 22, 30, 40],
    schaden: [2, 3, 5, 7, 10],
    speedFaktor: 0.95,
    waffe: "mg",
    reichweite: 4,
    feuerCooldown: 400,
    basis: true,
  },
  panzer: {
    key: "panzer",
    name: "Panzer",
    beschreibung: "Schwere Panzerung. Standardmäßig freigeschaltet.",
    farbe: "bg-zinc-600",
    freischaltApfel: 0,
    freischaltSternanis: 0,
    forschungSteigerung: 1.9,
    blattKosten: 5,
    sternanisBauAb4: 6,
    hp: [30, 42, 58, 78, 105],
    schaden: [0, 0, 0, 0, 0],
    speedFaktor: 0.85,
    waffe: "keine",
    reichweite: 0,
    feuerCooldown: 0,
    basis: true,
  },
  kettenhemd: {
    key: "kettenhemd",
    name: "Kettenhemd",
    beschreibung: "Reduziert eingehenden Schaden des gesamten Wurms.",
    farbe: "bg-stone-500",
    freischaltApfel: 25,
    freischaltSternanis: 0,
    forschungSteigerung: 2.2,
    blattKosten: 6,
    sternanisBauAb4: 6,
    hp: [18, 25, 34, 46, 62],
    schaden: [0, 0, 0, 0, 0],
    speedFaktor: 0.9,
    waffe: "keine",
    reichweite: 0,
    feuerCooldown: 0,
  },
  schall: {
    key: "schall",
    name: "Schallkanone",
    beschreibung: "Mittlere Reichweite, durchdringender Schaden.",
    farbe: "bg-cyan-600",
    freischaltApfel: 40,
    freischaltSternanis: 0,
    forschungSteigerung: 2.4,
    blattKosten: 8,
    sternanisBauAb4: 8,
    hp: [14, 19, 26, 35, 47],
    schaden: [3, 5, 7, 10, 14],
    speedFaktor: 0.93,
    waffe: "schall",
    reichweite: 3,
    feuerCooldown: 600,
  },
  laser: {
    key: "laser",
    name: "Laser",
    beschreibung: "Hohe Reichweite, präziser Schaden.",
    farbe: "bg-red-600",
    freischaltApfel: 70,
    freischaltSternanis: 0,
    forschungSteigerung: 2.6,
    blattKosten: 12,
    sternanisBauAb4: 10,
    hp: [13, 17, 23, 31, 42],
    schaden: [4, 6, 9, 13, 18],
    speedFaktor: 0.92,
    waffe: "laser",
    reichweite: 6,
    feuerCooldown: 700,
  },
  kastanie: {
    key: "kastanie",
    name: "Kastanie",
    beschreibung: "Fällt direkt am Segment herunter. Hoher Schaden.",
    farbe: "bg-amber-800",
    freischaltApfel: 35,
    freischaltSternanis: 0,
    forschungSteigerung: 2.2,
    blattKosten: 7,
    sternanisBauAb4: 7,
    hp: [15, 21, 28, 38, 51],
    schaden: [8, 12, 17, 24, 33],
    speedFaktor: 0.9,
    waffe: "kastanie",
    reichweite: 0,
    feuerCooldown: 1500,
  },
  raketenwerfer: {
    key: "raketenwerfer",
    name: "Raketenwerfer",
    beschreibung: "Sehr hohe Reichweite, Flächenschaden.",
    farbe: "bg-orange-700",
    freischaltApfel: 120,
    freischaltSternanis: 0,
    forschungSteigerung: 2.8,
    blattKosten: 18,
    sternanisBauAb4: 14,
    hp: [16, 22, 30, 40, 54],
    schaden: [10, 15, 21, 30, 42],
    speedFaktor: 0.88,
    waffe: "raketenwerfer",
    reichweite: 10,
    feuerCooldown: 1800,
  },
  gatling: {
    key: "gatling",
    name: "Gatling",
    beschreibung: "Schnellfeuer mit niedrigem Einzelschaden.",
    farbe: "bg-slate-400",
    freischaltApfel: 55,
    freischaltSternanis: 0,
    forschungSteigerung: 2.4,
    blattKosten: 10,
    sternanisBauAb4: 9,
    hp: [13, 18, 24, 32, 43],
    schaden: [1, 2, 3, 4, 6],
    speedFaktor: 0.93,
    waffe: "gatling",
    reichweite: 4,
    feuerCooldown: 150,
  },
  granatwerfer: {
    key: "granatwerfer",
    name: "Granatwerfer",
    beschreibung: "Flächen- & Feuerschaden über Zeit. Wirft 4 Felder weit.",
    farbe: "bg-orange-600",
    freischaltApfel: 90,
    freischaltSternanis: 0,
    forschungSteigerung: 2.6,
    blattKosten: 14,
    sternanisBauAb4: 12,
    hp: [14, 19, 26, 35, 47],
    schaden: [6, 9, 13, 18, 25],
    speedFaktor: 0.9,
    waffe: "granat",
    reichweite: 4,
    feuerCooldown: 1400,
  },
  stachel: {
    key: "stachel",
    name: "Stachelwerfer",
    beschreibung: "Giftschaden über Zeit.",
    farbe: "bg-lime-700",
    freischaltApfel: 60,
    freischaltSternanis: 0,
    forschungSteigerung: 2.3,
    blattKosten: 9,
    sternanisBauAb4: 8,
    hp: [12, 16, 22, 30, 40],
    schaden: [2, 3, 4, 6, 8],
    speedFaktor: 0.94,
    waffe: "stachel",
    reichweite: 3,
    feuerCooldown: 1000,
  },
  spinnenest: {
    key: "spinnenest",
    name: "Spinnenest",
    beschreibung: "Spawnt alle 8s eine Spinne, die feindliche Würmer & Baum angreift.",
    farbe: "bg-purple-700",
    freischaltApfel: 150,
    freischaltSternanis: 0,
    forschungSteigerung: 2.8,
    blattKosten: 16,
    sternanisBauAb4: 14,
    hp: [15, 20, 27, 36, 49],
    schaden: [3, 4, 6, 9, 12],
    speedFaktor: 0.88,
    waffe: "spinne",
    reichweite: 0,
    feuerCooldown: 8000,
  },
  honigpumpe: {
    key: "honigpumpe",
    name: "Honigpumpe",
    beschreibung: "Kein Schaden, verlangsamt Gegner um 60 % für 6 s. Reichweite 4.",
    farbe: "bg-yellow-500",
    freischaltApfel: 80,
    freischaltSternanis: 0,
    forschungSteigerung: 2.5,
    blattKosten: 11,
    sternanisBauAb4: 10,
    hp: [14, 19, 26, 35, 47],
    schaden: [0, 0, 0, 0, 0],
    speedFaktor: 0.92,
    waffe: "honig",
    reichweite: 4,
    feuerCooldown: 1200,
  },
  blasebalg: {
    key: "blasebalg",
    name: "Blasebalg",
    beschreibung: "Stößt kleinere Gegner 3 Segmente zurück. Kein Schaden.",
    farbe: "bg-sky-600",
    freischaltApfel: 50,
    freischaltSternanis: 0,
    forschungSteigerung: 2.3,
    blattKosten: 7,
    sternanisBauAb4: 7,
    hp: [12, 16, 22, 30, 40],
    schaden: [0, 0, 0, 0, 0],
    speedFaktor: 0.94,
    waffe: "blase",
    reichweite: 3,
    feuerCooldown: 1500,
  },
  larven: {
    key: "larven",
    name: "Larven",
    beschreibung: "Spawnt 3 Maden beim Tod des Wurms.",
    farbe: "bg-pink-600",
    freischaltApfel: 70,
    freischaltSternanis: 0,
    forschungSteigerung: 2.4,
    blattKosten: 9,
    sternanisBauAb4: 8,
    hp: [11, 15, 20, 27, 36],
    schaden: [2, 3, 4, 6, 8],
    speedFaktor: 0.94,
    waffe: "larven",
    reichweite: 0,
    feuerCooldown: 0,
  },
  flammenwerfer: {
    key: "flammenwerfer",
    name: "Flammenwerfer",
    beschreibung: "Flammen in 2 Feldern, Feuerschaden über Zeit.",
    farbe: "bg-red-700",
    freischaltApfel: 100,
    freischaltSternanis: 0,
    forschungSteigerung: 2.5,
    blattKosten: 13,
    sternanisBauAb4: 11,
    hp: [13, 18, 24, 32, 43],
    schaden: [5, 7, 10, 14, 20],
    speedFaktor: 0.9,
    waffe: "flamme",
    reichweite: 2,
    feuerCooldown: 800,
  },
};

export const ALLE_SEGMENT_KEYS = Object.keys(SEGMENTE) as SegmentKey[];
export const BASIS_SEGMENTE: SegmentKey[] = ["beine", "mg", "panzer"];

/** Forschungskosten für Stufe `stufe` (1..5) eines Segments. */
export function forschungskosten(
  key: SegmentKey,
  stufe: number,
): { apfel: number; sternanis: number } {
  const def = SEGMENTE[key];
  const f = Math.pow(def.forschungSteigerung, stufe - 1);
  return {
    apfel: Math.round(def.freischaltApfel * f),
    // Ab Stufe 4 Sternanis-Aufpreis
    sternanis: stufe >= 4 ? Math.round(def.sternanisBauAb4 * (stufe - 3) * 1.5) : 0,
  };
}

/** In-Battle Baukosten in Blättern (= Äpfel) und Sternanis ab Stufe 4. */
export function baukosten(
  key: SegmentKey,
  stufe: number,
): { blatt: number; sternanis: number } {
  const def = SEGMENTE[key];
  return {
    blatt: Math.round(def.blattKosten * Math.pow(1.25, stufe - 1)),
    sternanis: stufe >= 4 ? def.sternanisBauAb4 : 0,
  };
}
